### ISSUE TITLE
Running FUSE binary with -d gives random bytes and doesn't work

### ISSUE THREAD

**Issue by sidsenkumar11** [chippermist/SIGSEGV#41]
```
[centos@euca-10-1-5-166 SIGSEGV]$ ./bin/fuse -n 8388608 -f "/dev/vdc" "mpoint/" -d
fuse: unknown option `�∟Sk�'
```

**Comment by xavierholt** [comment]
Does this work if `mpoint` is the last option?  I think that might be required with the way the command line code is set up right now.

**Comment by sidsenkumar11** [comment]
I actually just fixed it a minutes ago on my PR!

I had added extra arguments to fs_mount() call, but hadn't extended the char *[] for argv, hence the problem. Just tested and it works now, so this is ready to close!
